moved ga script to a new branch, reverted to original, updated gs and gd

diff --git a/scripts/ga b/scripts/ga
--- a/scripts/ga
+++ b/scripts/ga
@@ -1,110 +1,99 @@
 #!/usr/bin/env bash
 
-PURPLE="\\033[0;35m"
-WHITE="\\033[0m"
+set -e
 
+PURPLE="\033[0;35m"
+WHITE="\033[0m"
+PORCELAIN=$(git status --porcelain 2>/dev/null)
+PORCELAINLIST=$(awk '{print $2}' <<< "$PORCELAIN")
 
-checkPorcelain(){
-    porcelain=$(git status --porcelain 2>/dev/null)
-    porcelainlist=$(awk '{print $NF}' <<< "$porcelain")
+header(){
+    echo -e "[${PURPLE}${1}${WHITE}]"
 }
 
-checkModified(){
-    echo -e "$porcelain" | grep "^ \\|^MM" | awk '{print $NF}'
-}
-
-checkUntracked(){
-    grep "^??" <<< "$porcelain" | awk '{print $NF}'
-}
-
-commitChanges(){
-    read -rp "$(header 'Commit changes? [Y/n/a]mend to previous commit, or enter commit message') " answer
-    case "$answer" in
-        "") git commit -v ;;
-        [Yy] ) git commit -v ;;
-        [Aa] ) git commit --amend ;;
-        [Nn] ) exit 1 ;;
-        *) git commit -m "$answer" ;;
-    esac
-    echo
-}
-
-fullStatus(){
-    checkPorcelain
-    if [ -z "$porcelain" ]; then
+fullstatus(){
+    if [ -z "$PORCELAIN" ]; then
         header "Git Show - Latest Commit"
         gitcheck show
         echo
     else
         header "Git Diff/Staged"
         gitcheck diff HEAD
-        echo
     fi
     header "Git Status"
     gitcheck status
     echo
-    [ "$porcelain" ] \
+    [ "$PORCELAIN" ] \
     && header "Porcelain Status" \
-    && echo -e "$porcelain"
-    showPreviousCommit
+    && echo -e "$PORCELAIN"
 }
 
 gitcheck(){
     git -c color."$1"=always --no-pager "$@"
 }
 
-header(){
-    echo -e "[${PURPLE}${1}${WHITE}]"
+checkStaged(){
+    unstaged=$(echo -e "$PORCELAIN" | grep "^ \|^MM")
+    if [ "$unstaged" ]; then
+        header "Staging Modified"
+        echo -e "$PORCELAINLIST\n"
+        git add --patch "$1" 2>/dev/null # without sending error to null,
+        # i get this before running the add:
+        # warning: empty strings as pathspecs will be made invalid in upcoming releases.
+        # please use . instead if you meant to match all paths
+    fi
+}
+
+checkTracked(){
+    untracked=$(echo -e "$PORCELAIN" | grep "^??")
+    if [ "$untracked" ]; then
+        header "Staging Untracked: $1"
+        git add "$1"
+    fi
 }
 
 main(){
-    checkPorcelain
-    if [ -z "$porcelain" ]; then
-        header "No modified or untracked files, showing latest commit on branch"
-        git --no-pager log -1 --oneline --decorate
-        return 1
-    else
-        if [ "$TO_STAGE" ]; then # stage files if specified
-            TO_STAGE="$*"
-        else # stage all porcelain files if none specified
-            TO_STAGE="."
+    if [ "$PORCELAIN" ]; then
+        # echo "$PORCELAINLIST"
+        if [ ! "$1" ]; then # stage all files if none specified
+            checkStaged .
+            checkTracked .
+        elif [[ $PORCELAINLIST =~ $1 ]]; then
+            filename=$(echo "${PORCELAINLIST/$'\n'/ }" | grep "$1")
+            checkStaged $filename # must be without quotes
+            checkTracked $filename # must be without quotes
+            exit 0 # testing
+        else
+            echo "[WARN] invalid file: \"$1\""
+            exit 1
         fi
-        stageFiles "$TO_STAGE"
-        checkPorcelain
-        showPreviousCommit
-        commitChanges
-        fullStatus
-    fi
-}
-
-showPreviousCommit(){
-    header "Previous Git Commit"
-    git --no-pager log -1 --oneline --decorate
-    echo
-}
-
-stageFiles(){
-    header "Staging Modified/Untracked Files"
-    if [ "$TO_STAGE" = "." ]; then
-        git add --patch .
+        # break this out to an if check
+            header "Porcelain Status"
+            # newstatus=git status --porcelain 2>/dev/null
+            git status --porcelain
+        echo
+        header "Previous Git Commit"
+        # git show @~
+        git --no-pager log -1 --oneline --decorate
+        read -rp "$(header 'Commit changes? [Y/n/a]mend to previous commit') " yna
+        echo
+        if [ -z "$yna" ]; then # default option if no argument is passed
+            git commit -v
+        else
+            case "${yna}" in
+                [Yy]*)  git commit -v ;;
+                [Aa]*)  git commit --amend ;;
+                [Nn]*)  return 0 ;;
+                *)  echo "invalid entry, try again"; main ;;
+            esac
+        fi
     else
-        modified=$(checkModified)
-        while read -r line; do
-            grep -w "$line" <<< "$TO_STAGE" >/dev/null && \
-                staging_modified+="$line "
-        done <<< "$modified"
+        header "No unstaged or untracked files, showing latest commit on branch"
+        git --no-pager log -1 --oneline --decorate
+        echo
     fi
-    [ "$staging_modified" ] && \
-        git add --patch $staging_modified 2>/dev/null # git 128 error if quoted
-
-    untracked=$(checkUntracked)
-    while read -r line; do
-        grep -w "$line" <<< "$TO_STAGE" >/dev/null && \
-            staging_untracked+="$line "
-    done <<< "$untracked"
-    [ "$staging_untracked" ] && \
-        git add $staging_untracked 2>/dev/null # git 128 error if quoted
 }
 
 
-main "$TO_STAGE"
+# make $PORCELAIN a function
+main "${@}" && [ "$PORCELAIN" ] # && fullstatus
diff --git a/scripts/gd b/scripts/gd
--- a/scripts/gd
+++ b/scripts/gd
@@ -2,15 +2,31 @@
 # quick git diff
 
 set -e
+set -x
+
+COMMIT_1="$1"
+COMMIT_2="$2"
+INTEGER='^[0-9]+$'
+
+
+# if ! [[ $COMMIT =~ $INTEGER ]] ; then
+#    echo "error: Not a number" >&2; exit 1
+# fi
+
+# exit 0
 
 git_diff(){
-    if [ "$2" ]; then
+    if [ "$COMMIT_2" ]; then
         # $1==older commit
         # $2==newer commit
-        git diff "$1"^ "$2"
-    elif [ "$1" ]; then
-        # only specific commit
-        git diff "$1"^ "$1"
+        git diff "$COMMIT_1"^ "$COMMIT_2"
+    elif [ "$COMMIT_1" ]; then
+        # if [[ $COMMIT_1 =~ $INTEGER ]] ; then
+        #     echo git diff # number of most recent commit
+        # else
+            # only specific commit
+            git diff "$1"^ "$1"
+        # fi
     else
         # latest commit
         git diff HEAD^ HEAD
